# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-08 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epidemiology', '0004_remove_epi_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='epi',
            old_name='titl',
            new_name='title',
        ),
    ]
